# Generated by Django 4.2.7 on 2023-11-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='stock',
        ),
    ]
